#### N维数组是机器学习和神经网络的主要数据结构

创建数组
1. 形状
2. 每个元素的数据类型
3. 每个元素的值

In [2]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape  # 通过shape来访问张量的形状

torch.Size([12])

In [7]:
x.numel() # 通过numel来访问张量元素的个数

12

通过reshape来改变一个张量的形状而不改变元素数量和元素值

In [8]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0，全1，其他常量或者从特定分布中随机采样的数字

In [10]:
torch.zeros((2,3,4))  # 创建了一个全0的三维数组

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))  # 创建了一个全1的三维数组

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [ ]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]) # 列表嵌套列表 -->二维数组

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [14]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) 

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [15]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]).shape

torch.Size([1, 3, 4])

常见的标准算术运算符（+, -, *, /, **） 都可以被升级为按元素运算

In [31]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x,y

(tensor([1., 2., 4., 8.]), tensor([2, 2, 2, 2]))

In [26]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [27]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [28]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [29]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [30]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [33]:
torch.exp(x)  # 可以按元素执行更多运算，eg.按指数

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量连结在一起

In [37]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [ ]:
torch.cat((X,Y),dim=0)  # dim = 0, 表示在列上做拼接，竖着拼

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [ ]:
torch.cat((X,Y),dim=1) # dim = 0, 表示在行上做拼接，横着拼

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

通过逻辑运算符来构建二维的张量

In [39]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素求和会产生一个只有一个元素的张量

In [40]:
X.sum()

tensor(66.)

对于形状不同的张量，可以通过调用 *广播机制*  来执行按元素的操作

In [41]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b  # 背后是把 a 的那一列复制一列，复制成一个3*2的矩阵
       # 把 b 的那一行复制两行，也复制成一个 3*2 的矩阵

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##### 访问元素

In [ ]:
X[-1]   # 使用 -1 访问最后一个元素

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [46]:
X[1:3]  # 使用1：3访问第二个和第三个元素

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

指定索引来将元素写入矩阵

In [47]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [49]:
X[1, 2] = 99
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 99.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素指定相同的值

In [50]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致为新结果分配内存

In [ ]:
before = id(Y)  # id类似于C语言中的指针
Y = Y + X
if(Y) == before